// Copyright 2022 beekeeb
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1


#define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 0

#define LEADER_KEY_STRICT_KEY_PROCESSING
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define COMBO_TERM 55
#define COMBO_ONLY_FROM_LAYER 0

#define TAP_CODE_DELAY 15

#define FLOW_COUNT 12
#define FLOW_LAYERS_COUNT 6
